version: '3.8'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    
    environment: 
      - "DJANGO_SECRET_KEY=IA4bkb8JbeG9vp_2toOVo5ergAEgTikfa3rsh-QQR9ACliARVvs"
      - "DJANGO_DEBUG=False"
    volumes:
      - .:/code
    ports:
      - 8000:8000
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
